version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  client:
    ports:
      - "5001:3000"
    
  proxy:  
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  
  postgres_db:
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

volumes:
  postgres-data:
  