version: "3.9"

services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: order-create-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:




# version: "3.9"

# networks:
#   order-create-dev:
#     driver: bridge

# services:
#   app: 
#     container_name: order-create-test
#     build:
#       context: .    
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#     networks:
#       - order-create-dev
#     depends_on:
#       - postgres_db
#   postgres_db:
#     container_name: postgres
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: order-create-test
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 1234
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - order-create-dev

# volumes:
#   postgres-data:

